spring:
  sql:
    init:
      schemaLocations: classpath*:db/h2/schema.sql

logging:
  level:
    org:
      springframework:
        DEBUG
      io.r2dbc.h2.QUERY: DEBUG
      io.r2dbc.h2.PARAM: DEBUG